
Settings:
  Vanish:
    FakeLeaveMessage: "&e%player% left the game"
    FakeJoinMessage: "&e%player% joined the game"
    SilentJoinMessage: "&8%player% &3Silently joined the game"
    HideFromCommands: true
    HiddenCommands:
      - tpa
      - msg
      - message
      - tpahere
      - w
      - whisper
      - tell
      - t


  VillagerTrades:
    DemandPenalty: true
    InstantRestock: false

    AddedTrades: {}
#     cleric: {}
#       gunpowder:
#         amount: 5
#         price: 3
#         currency: emerald
#         chance: 0.5
#         maxuses: 25
#         lvl: 5
#       redstone:
#         amount: 4
#         price: 2
#         currency: emerald
#         chance: 0.7 #= 70%
#         maxuses: 12
#         lvl: 3

# Manage those who use xaeros minimap
Xaero:
  mode: none # (fairplay/netheronly/disabled/none)